In [1]:
import numpy as np

# Створення двох масивів розміром 5 з випадковими цілими числами від 1 до 30
array1 = np.random.randint(1, 31, size=5)
array2 = np.random.randint(1, 31, size=5)

# Виконання поелементної операції додавання
addition_result = array1 + array2

# Виконання поелементної операції віднімання
subtraction_result = array1 - array2

# Виконання поелементної операції множення
multiplication_result = array1 * array2

array1, array2, addition_result, subtraction_result, multiplication_result


(array([10, 10,  1,  8,  2]),
 array([ 1, 27,  6, 17, 16]),
 array([11, 37,  7, 25, 18]),
 array([  9, -17,  -5,  -9, -14]),
 array([ 10, 270,   6, 136,  32]))