In [1]:
import numpy as np

# Створення першої матриці 2x2 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))

# Створення другої матриці 2x2 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Знайдення різниці елементів обох матриць
difference = matrix1 - matrix2

matrix1, matrix2, difference


(array([[6, 7],
        [9, 5]]),
 array([[4, 4],
        [6, 3]]),
 array([[2, 3],
        [3, 2]]))