In [1]:
import numpy as np

# Створення двох матриць 2x3 та 3x2 з випадковими цілими числами від 1 до 15
matrix1 = np.random.randint(1, 16, size=(2, 3))
matrix2 = np.random.randint(1, 16, size=(3, 2))

# Множення двох матриць
result_matrix = np.dot(matrix1, matrix2)

matrix1, matrix2, result_matrix


(array([[ 8, 13,  7],
        [ 2,  9,  4]]),
 array([[ 2, 10],
        [ 9, 12],
        [ 4,  4]]),
 array([[161, 264],
        [101, 144]]))