In [2]:
import numpy as np
import sympy as sp

# Створення першої матриці 3x3 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(3, 3))

# Створення другої матриці 3x3 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(3, 3))

# Обчислення добутку всіх елементів обох матриць за допомогою sympy
product = sp.prod(matrix1) * sp.prod(matrix2)

matrix1, matrix2, product


(array([[ 1,  6,  1],
        [ 9, 10,  9],
        [ 8,  5,  1]]),
 array([[10,  4,  7],
        [10,  2,  2],
        [ 9,  1,  9]]),
 array([64800,  2400,  1134]))